### ISSUE TITLE
Get-Authtoken not working at all

### ISSUE THREAD

**Issue by nlmaca** [UiPath/orchestrator-powershell#10]
Maybe i am missing something. I don't get an authtoken when i try to get it. The command returns an emtpy value
release used: https://github.com/UiPath/orchestrator-powershell/releases/tag/v18.1.3.21046

My server(s) setup
Windows Server 2016 - UiPath Orchestrator(no license - they don't handout trial licenses for the orchestrator server :()
Windows Server 2016 - Uipath Studio with UiRobot
1 normal admin user and a windows user (AD import), both have the administrator Role and the logins are working. 

The problem: i can't get a Authtoken with either of the accounts. 
I tried all of them: 
https://github.com/UiPath/orchestrator-powershell/blob/master/docs/Get-UiPathAuthToken.md

The token doesn't get set. It returns blank. 
When i try to run an example command from the link above it returns empty. When i run the next command i get errors like this: 
```
Get-UiPathEnvironment : An authentication token is required. Specify a value for -AuthToken on the cmdlet or call Set-UiPathAuthToken for the 
session
At line:1 char:1
+ Get-UiPathEnvironment
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-UiPathEnvironment], Exception
    + FullyQualifiedErrorId : System.Exception,UiPath.PowerShell.Cmdlets.GetEnvironment
```
This command also doesnt work: 
Get-Help -Module UiPath.PowerShell
```
Get-Help : A parameter cannot be found that matches parameter name 'Module'.
At line:1 char:10
+ Get-Help -Module UiPath.PowerShell
+          ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Help], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetHelpCommand

```
Are there some Prerequisites i need to have on the Orchestrator Server?

**Comment by ratzinho87** [comment]
What version of Powesrhell do you have? Did you try the latest version?

**Comment by nlmaca** [comment]
Hi ratzinho87. See my first note. Release used: https://github.com/UiPath/orchestrator-powershell/releases/tag/v18.1.3.21046 which is the latest

Powershell version: 
Version          : 5.1.14393.2273

**Comment by rusanu** [comment]
@nlmaca Try out `Get-UiPathAuthToken .... -Verbose` for extra debug output and post here the result.

**Comment by rusanu** [comment]
@nlmaca  use [`Get-Command -Module UiPath.PowerShell`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-command?view=powershell-6)

**Comment by nlmaca** [comment]
Thx @rusanu. It points me to a faulty SSL. 

`The underlying connection was closed: Could 
not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid accord
ing to the validation procedure.`

So at this point i have to fix my SSL certificate. Im using a selfsigned certificate at this point and  will setup a letsencrypt certificate tomorrow. Got some debugging to do and will let you know in the next couple of days. 

Does it matter that my setup doesn't have a UiOrchestrator license? Or do the Powershell scripts require a licensed Orchestrator?

Below the result with the -Verbose enabled. when i do an Get-UiPathAuthToken. Now i'm able to debug :D. Thx!

`VERBOSE: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could 
not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid accord
ing to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Web.Client.Account.<AuthenticateWithHttpMessagesAsync>d__5.MoveNext() in C:\git\orchestrator-powershell\UiPath.Web.Client\generated\Account.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Web.Client.AccountExtensions.<AuthenticateAsync>d__1.MoveNext() in C:\git\orchestrator-powershell\UiPath.Web.Client\generated\AccountExtensions.cs:line 5
2
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UiPath.Web.Client.AccountExtensions.Authenticate(IAccount operations, LoginModel loginModel) in C:\git\orchestrator-powershell\UiPath.Web.Client\generated\Accou
ntExtensions.cs:line 32
   at UiPath.PowerShell.Util.UiPathCmdlet.HandleHttpOperationException[T](Func`1 action) in C:\git\orchestrator-powershell\UiPath.PowerShell\Util\UiPathCmdlet.cs:line
 17
   at UiPath.PowerShell.Cmdlets.GetAuthToken.GetUserToken() in C:\git\orchestrator-powershell\UiPath.PowerShell\Cmdlets\GetAuthToken.cs:line 162
   at UiPath.PowerShell.Cmdlets.GetAuthToken.ProcessRecord() in C:\git\orchestrator-powershell\UiPath.PowerShell\Cmdlets\GetAuthToken.cs:line 75`

**Comment by nlmaca** [comment]
@ratzinho87  and @rusanu The problem for the Get-AuthToken was indeed in the SSL certificate. A selfsigned SSL isnt valid within a domain, but i didn't know it would give a problem for the AuthToken even when i just connected to the ipadress of the server. 
I installed a letsencrypt certificate on the IIS and at this point im getting a token back on the default admin. So the issue is solved for now.
Would it be a request for errorhandling that if the SSL certificate isn't valid, a message would show that the SSL might not be valid?

From my end the ticket is solved. Thx for directions
